### PR TITLE
Update helper.php: utf8_strtolower() is deprecated warning

### PR DESCRIPTION
**Pull request by nerun**
Fix deprecation warning:

```
utf8_strtolower() is deprecated. It was called from helper_plugin_captcha::check() in /lib/plugins/captcha/helper.php:153 dokuwiki\Utf8\PhpString::strtolower() should be used instead!
```

### CODE REVIEW

**Review by splitbrain — CHANGES_REQUESTED** [review]
No. The better fix is to use the UTF8 classes.

**Review by splitbrain — CHANGES_REQUESTED** [review]
nope. did you read the full message in your original post? It already tells you what to use instead!

**Comment by nerun** [comment]
Forgive me. Should i use JUST `strtolower()` and nothing else?

**Comment by splitbrain** [comment]
> utf8_strtolower() is deprecated. It was called from helper_plugin_captcha::check() in /lib/plugins/captcha/helper.php:153 dokuwiki\Utf8\PhpString::strtolower() should be used instead!

What is unclear about this message?

**Pull request merged**
